const SUPABASE_URL='https://khhvwjvajqigdsnbnzui.supabase.co';
const SUPABASE_KEY='sb_publishable_DNO-I64XmvqELYnvVQNb1g_U0jK6Qel';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null;let tickets=[];
const $=id=>document.getElementById(id);
const safe=value=>String(value??'').replace(/[&<>\"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[ch]));
function badge(status){const cls=status==='Closed / Resolved'?'done':status==='Scheduled'?'wait':status==='Quotation Required'?'quote':'';return `<span class="badge ${cls}">${safe(status||'Open')}</span>`}
function age(date){return Math.max(0,Math.floor((Date.now()-new Date(date).getTime())/86400000))}
function render(){const q=$('search').value.toLowerCase(),s=$('statusFilter').value;const list=tickets.filter(t=>{const hay=[t.ticket_number,t.external_ticket_number,t.case_number,t.client_company,t.location,t.job_type].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!s||t.status===s)});$('openCount').textContent=tickets.filter(t=>['New (email)','Open','Seen'].includes(t.status)).length;$('scheduledCount').textContent=tickets.filter(t=>t.status==='Scheduled').length;$('quoteCount').textContent=tickets.filter(t=>t.status==='Quotation Required').length;$('resolvedCount').textContent=tickets.filter(t=>t.status==='Closed / Resolved').length;$('emptyState').classList.toggle('hidden',list.length>0);$('ticketRows').innerHTML=list.map(t=>`<tr data-id="${safe(t.id)}"><td><b class="ticket-link">${safe(t.internal_ticket_number)}</b></td><td>${safe(t.case_number)}</td><td>${safe(t.client_company)}</td><td>${safe(t.location)}</td><td title="${safe(t.job_type)}">${safe(t.job_type)}</td><td>${badge(t.status)}</td><td>${age(t.updated_at||t.created_at)}d</td></tr>`).join('');document.querySelectorAll('#ticketRows tr').forEach(row=>row.addEventListener('click',()=>showDetail(tickets.find(t=>String(t.id)===row.dataset.id))))}
async function loadTickets(){const {data,error}=await db.from('personal_tickets').select('*').order('created_at',{ascending:false});if(error)throw error;tickets=data||[];render()}
function parseEmail(){const raw=$('emailText').value;const pick=(patterns)=>{for(const p of patterns){const m=raw.match(p);if(m)return m[1].trim()}return''};$('caseNumber').value=pick([/Case\s*#\s*([^\n]+)/i]);$('externalTicket').value=pick([/Ticket\s*#:\s*([^\n]+)/i]);$('clientCompany').value=pick([/Company:\s*([^\n]+)/i]);$('location').value=pick([/Address:\s*([^\n]+)/i]);$('jobType').value=pick([/Created:\s*([^\n]+)/i]);}
function showDetail(t){if(!t)return;$('detailTitle').textContent=t.internal_ticket_number||'Ticket';$('detailBody').innerHTML=`<div class="detail-grid"><p><b>External ticket:</b> ${safe(t.external_ticket_number)}</p><p><b>Case:</b> ${safe(t.case_number)}</p><p><b>Client:</b> ${safe(t.client_company)}</p><p><b>Location:</b> ${safe(t.location)}</p><p><b>Job type:</b> ${safe(t.job_type)}</p><p><b>Status:</b> ${safe(t.status)}</p><p class="wide"><b>Notes:</b><br>${safe(t.notes)}</p></div>`;$('detailDialog').showModal()}
async function createTicket(event){event.preventDefault();$('ticketError').textContent='';const {data:session}=await db.auth.getSession();if(!session.session){$('ticketError').textContent='Please sign in again.';return}const row={external_ticket_number:$('externalTicket').value.trim(),case_number:$('caseNumber').value.trim(),client_company:$('clientCompany').value.trim(),location:$('location').value.trim(),job_type:$('jobType').value.trim(),status:'New (email)',email_body:$('emailText').value,created_by:session.session.user.id,updated_at:new Date().toISOString()};const {error}=await db.from('personal_tickets').insert(row);if(error){$('ticketError').textContent=error.message;return}$('ticketDialog').close();$('ticketForm').reset();await loadTickets()}
async function login(email,password){const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;currentUser=data.user;$('userEmail').textContent=email;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');await loadTickets()}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginError').textContent='';try{await login($('loginEmail').value,$('loginPassword').value)}catch(error){$('loginError').textContent=error.message}});$('ticketForm').addEventListener('submit',createTicket);$('emailText').addEventListener('blur',parseEmail);$('newTicketButton').addEventListener('click',()=>$('ticketDialog').showModal());$('newTicketNav').addEventListener('click',()=>$('ticketDialog').showModal());$('search').addEventListener('input',render);$('statusFilter').addEventListener('change',render);$('refresh').addEventListener('click',()=>loadTickets().catch(error=>alert(error.message)));$('signOut').addEventListener('click',async()=>{await db.auth.signOut();location.reload()});
