-- Personal Field Desk v2. Uses separate tables; legacy ticket tables remain unchanged.
create table if not exists public.personal_tickets (
  id bigint generated by default as identity primary key,
  internal_ticket_number text not null unique,
  external_ticket_number text,
  case_number text,
  client_company text,
  contact_name text,
  contact_phone text,
  department text,
  location text,
  job_type text,
  status text not null default 'New (email)',
  email_subject text,
  email_body text,
  notes text,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create sequence if not exists public.personal_ticket_seq;
create or replace function public.personal_ticket_number() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$ begin new.internal_ticket_number:='JOB-'||to_char(coalesce(new.created_at,now()),'YYYY')||'-'||lpad(nextval('public.personal_ticket_seq')::text,6,'0'); return new; end; $$;
drop trigger if exists personal_ticket_number_trigger on public.personal_tickets;
create trigger personal_ticket_number_trigger before insert on public.personal_tickets for each row execute function public.personal_ticket_number();
alter table public.personal_tickets enable row level security;
drop policy if exists "Personal users view own tickets" on public.personal_tickets;
drop policy if exists "Personal users create own tickets" on public.personal_tickets;
drop policy if exists "Personal users update own tickets" on public.personal_tickets;
create policy "Personal users view own tickets" on public.personal_tickets for select to authenticated using (created_by=auth.uid());
create policy "Personal users create own tickets" on public.personal_tickets for insert to authenticated with check (created_by=auth.uid());
create policy "Personal users update own tickets" on public.personal_tickets for update to authenticated using (created_by=auth.uid()) with check (created_by=auth.uid());
